language: node_js
node_js:
- '4.0'
- '8.0'
sudo: false
deploy:
  provider: releases
  api_key:
    secure: V5d7+reDV7FALlf4DQgJe+yXE12ySC0TCZbqbPzbDifCftWNnCceWJNdGkfrupbQ2+vtbwzjll9GSf3h6FkoM8kLebjTiv2uvmtJQDs3PvwMGb2fgjNonHmQextqys2uBYyZDucek/xHHPDafEAvptXX0IKtBnsBBcEdP0BihXI=
  file:
    - "emoticon.js"
    - "emoticon.min.js"
  on:
    tags: true
    node: '8.0'
